// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/ozosanek/ozon_task/internal/domain"
)

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Node   *domain.Comment `json:"node"`
	Cursor Cursor          `json:"cursor"`
}

type CreateCommentInput struct {
	PostID     string  `json:"postId"`
	ParentID   *string `json:"parentId,omitempty"`
	AuthorName string  `json:"authorName"`
	Body       string  `json:"body"`
}

type CreatePostInput struct {
	AuthorName      string `json:"authorName"`
	Title           string `json:"title"`
	Body            string `json:"body"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *Cursor `json:"endCursor,omitempty"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Node   *domain.Post `json:"node"`
	Cursor Cursor       `json:"cursor"`
}

type Query struct {
}

type Subscription struct {
}

type UpdatePostCommentsEnabledInput struct {
	PostID          string `json:"postId"`
	AuthorName      string `json:"authorName"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}
