package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/ozosanek/ozon_task/internal/domain"
	"github.com/ozosanek/ozon_task/internal/graph/generated"
	"github.com/ozosanek/ozon_task/internal/graph/model"
	"github.com/ozosanek/ozon_task/internal/storage"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *domain.Comment, first int, after *model.Cursor) (*model.CommentConnection, error) {
	page, err := r.service.ListComments(ctx, obj.PostID, &obj.ID, listOptions(first, after))
	if err != nil {
		return nil, err
	}

	return commentConnection(page), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*domain.Post, error) {
	post, err := r.service.CreatePost(ctx, storage.CreatePostParams{
		AuthorName:      input.AuthorName,
		Title:           input.Title,
		Body:            input.Body,
		CommentsEnabled: input.CommentsEnabled,
	})
	if err != nil {
		return nil, err
	}

	return &post, nil
}

// UpdatePostCommentsEnabled is the resolver for the updatePostCommentsEnabled field.
func (r *mutationResolver) UpdatePostCommentsEnabled(ctx context.Context, input model.UpdatePostCommentsEnabledInput) (*domain.Post, error) {
	post, err := r.service.UpdatePostCommentsEnabled(ctx, input.PostID, input.AuthorName, input.CommentsEnabled)
	if err != nil {
		return nil, err
	}

	return &post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*domain.Comment, error) {
	comment, err := r.service.CreateComment(ctx, storage.CreateCommentParams{
		PostID:     input.PostID,
		ParentID:   input.ParentID,
		AuthorName: input.AuthorName,
		Body:       input.Body,
	})
	if err != nil {
		return nil, err
	}

	return &comment, nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *domain.Post, first int, after *model.Cursor) (*model.CommentConnection, error) {
	page, err := r.service.ListComments(ctx, obj.ID, nil, listOptions(first, after))
	if err != nil {
		return nil, err
	}

	return commentConnection(page), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int, after *model.Cursor) (*model.PostConnection, error) {
	page, err := r.service.ListPosts(ctx, listOptions(first, after))
	if err != nil {
		return nil, err
	}

	return postConnection(page), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*domain.Post, error) {
	post, err := r.service.GetPost(ctx, id)
	if err != nil {
		return nil, err
	}

	return &post, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *domain.Comment, error) {
	return r.service.SubscribeComments(ctx, postID)
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
